### ISSUE TITLE
Inserting quote data

### ISSUE THREAD

**Issue by mscappini** [aisthesis/optbot#6]
2015-04-02 12:05:49,898 INFO quotes.updateeq :  Downloading options quotes for 'tsla'
2015-04-02 12:06:11,252 INFO quotes.updateeq :  Inserting quotes for 'tsla' into 'quotes'
2015-04-02 12:06:11,293 ERROR quotes.updateeq :  unknown exception
Traceback (most recent call last):
  File ".\quotes.py", line 150, in updateeq
    _result = _bulk.execute()
  File "C:\Users\Mark.virtualenvs\optbot\lib\site-packages\pymongo\bulk.py", line 587, in execute
    return self.__bulk.execute(write_concern)
  File "C:\Users\Mark.virtualenvs\optbot\lib\site-packages\pymongo\bulk.py", line 433, in execute
    return self.execute_command(generator, write_concern)
  File "C:\Users\Mark.virtualenvs\optbot\lib\site-packages\pymongo\bulk.py", line 288, in execute_command
    run.op_type, cmd, run.ops, True, uuid_subtype, client)
bson.errors.InvalidDocument: Cannot encode object: 0

**Comment by aisthesis** [comment]
That's the error I was getting when I was using the wrong pymongo version, but backing up to 2.8 and using python 2.7 made it work. You're not using Python 3?

If you're using the updates I made last night to resolve some datetime issues, it's also conceivable that that might be causing it, because I'm using `pytz` to force the timezone and hoping that they are compatible with the BSON conversion. They should be, as `pymongo` claims to support it as long as it's a python `datetime.datetime`. But I'll be interested to see what happens on today's run on the server with the updated code.

I think I'm going to file another issue to create a mock db that allows running multiple times a day for quick testing without corrupting your prod data.
